apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sokos-up-container
  namespace: okonomi
  labels:
    team: okonomi
spec:
  groups:
    - name: sokos-up-container-alerts
      rules:
        - alert: Applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="sokos-up-container"} == 0
          for: 2m
          annotations:
            action: "Sjek hvorfor applikasjonen er nede"
            summary: "App {{ $labels.deployment }} er nede i namespace {{ $labels.namespace }}"
          labels:
            namespace: okonomi
            severity: danger
            sokos_up_container_type: sokos-up-container
            alert_type: custom

        - alert: Applikasjonen har restartet flere ganger de siste 5 minuttene!
          expr: sum(increase(kube_pod_container_status_restarts_total{container=~"sokos-up-container"}[5m])) by (container) > 2
          for: 2m
          annotations:
            action: "Sjekk hvorfor applikasjonen ikke klarer å restarte"
            summary: "App {{ $labels.container }} restarter mange ganger"
          labels:
            namespace: okonomi
            severity: danger
            sokos_up_container_type: sokos-up-container
            alert_type: custom

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sokos-up-container-slack
  namespace: okonomi
  labels:
    alertmanagerConfig: sokos-up-container-slack
spec:
  receivers:
    - name: sokos-up-container-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#team-mob-alerts-prod'
          iconEmoji: ':alert:'
          username: 'Alert prod-gcp'
          sendResolved: true
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}
            {{ if or .Annotations.summary .Annotations.message }}
            {{ or .Annotations.summary .Annotations.message }}
            {{ println " " }}
            {{- end }}
            {{- if .Annotations.action }}
            • *action*: {{ .Annotations.action }} {{ println " " }}
            {{- end }}
            {{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "sokos_up_container_type"
        matchType: "="
        value: "sokos-up-container"
    groupInterval: 10s
    groupWait: 5s
    receiver: sokos-up-container-receiver
    repeatInterval: 2m
