apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-utbetalingsportalen
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  liveness:
    path: /utbetalingsportalen/internal/isAlive
    initialDelay: 10
  readiness:
    path: /utbetalingsportalen/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "6c93762e-ea37-4043-919f-3a758a136943" # 0000-GA-SOKOS-MF-Skattekort-READ
          - id: "25723642-e1da-4d15-87ce-8c4d2b87e33a" # 0000-GA-SOKOS-MF-PosteringSok-READ
          - id: "bb9c7baf-768b-4e84-816c-f10d0a6c7d25" # 0000-GA-SOKOS-MF-KRP-READ
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
  accessPolicy:
    outbound:
      rules:
        - application: sokos-up-ors-api
        - application: sokos-up-kontoregister-api
      external:
        - host: sokos-skattekort-person.prod-fss-pub.nais.io
  ingresses:
    - "https://utbetalingsportalen.intern.nav.no"
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  env:
    # sokos-up-ors-api
    - name: SOKOS_UP_ORS_API
      value: http://sokos-up-ors-api
    - name: SOKOS_UP_ORS_API_SCOPE
      value: api://prod-gcp.okonomi.sokos-up-ors-api/.default
    - name: SOKOS_UP_ORS_API_PROXY
      value: "/up-ors-api"

    # sokos-up-kontoregister-api
    - name: SOKOS_KONTOREGISTER_API
      value: http://sokos-up-kontoregister-api
    - name: SOKOS_KONTOREGISTER_API_SCOPE
      value: api://prod-gcp.okonomi.sokos-up-kontoregister-api/.default
    - name: SOKOS_KONTOREGISTER_API_PROXY
      value: "/up-kr-api"

    # Skattekort
    - name: SOKOS_SKATTEKORT_PERSON_API
      value: https://sokos-skattekort-person.prod-fss-pub.nais.io
    - name: SOKOS_SKATTEKORT_PERSON_API_SCOPE
      value: api://prod-fss.okonomi.sokos-skattekort-person/.default
    - name: SOKOS_SKATTEKORT_PROXY
      value: "/skattekort-api"
