apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-op-fasade
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /okonomiportalen/internal/isAlive
    initialDelay: 10
  readiness:
    path: /okonomiportalen/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "1b717a23-d376-471c-9fc6-356299fadc2b" # 0000-GA-SOKOS-MF-Mikrofrontend-READ
          - id: "1d1af049-4539-4988-a1db-b5bf3066322c" # 0000-GA-SOKOS-MF-Skattekort-READ
          - id: "b01fb216-fcb3-4ede-b7da-71fffe859763" # 0000-GA-SOKOS-MF-PosteringSok-READ
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
  accessPolicy:
    outbound:
      rules:
        - application: sokos-mikrofrontend-api
        - application: sokos-postering-api
      external:
        - host: sokos-skattekort-person.dev-fss-pub.nais.io
  ingresses:
    - "https://okonomiportalen.intern.dev.nav.no"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  env:

  # Mikrofrontend-template
  - name: SOKOS_MIKROFRONTEND_API
    value: http://sokos-mikrofrontend-api
  - name: SOKOS_MIKROFRONTEND_API_SCOPE
    value: api://dev-gcp.okonomi.sokos-mikrofrontend-api/.default
  - name: SOKOS_MIKROFRONTEND_PROXY
    value: "/mikrofrontend-api"

  # sokos-postering-api
  - name: SOKOS_POSTERING_API
    value: http://sokos-postering-api
  - name: SOKOS_POSTERING_API_SCOPE
    value: api://dev-gcp.okonomi.sokos-postering-api/.default
  - name: SOKOS_POSTERING_PROXY
    value: "/postering-api"

  # Skattekort
  - name: SOKOS_SKATTEKORT_PERSON_API
    value: https://sokos-skattekort-person.dev-fss-pub.nais.io
  - name: SOKOS_SKATTEKORT_PERSON_API_SCOPE
    value: api://dev-fss.okonomi.sokos-skattekort-person/.default
  - name: SOKOS_SKATTEKORT_PROXY
    value: "/skattekort-api"
