apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-op-fasade
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /okonomiportalen/internal/isAlive
    initialDelay: 10
  readiness:
    path: /okonomiportalen/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "5b9de9d1-8ef7-4f93-a96b-6ccea210e1cf" # 0000-GA-SOKOS-OP-FASADE
          - id: "6c93762e-ea37-4043-919f-3a758a136943" # 0000-GA-SOKOS-MF-Skattekort-READ
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
  accessPolicy:
    outbound:
      external:
        - host: sokos-skattekort-person.prod-fss-pub.nais.io
  ingresses:
    - "https://okonomiportalen.intern.nav.no"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  env:

    - name: MILJO
      value: prod-gcp

    # Skattekort
    - name: SOKOS_SKATTEKORT_PERSON_API
      value: https://sokos-skattekort-person.prod-fss-pub.nais.io
    - name: SOKOS_SKATTEKORT_PERSON_API_SCOPE
      value: api://prod-fss.okonomi.sokos-skattekort-person/.default
    - name: SOKOS_SKATTEKORT_PROXY
      value: "/skattekort-api"
