apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-op-fasade
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /okonomiportalen/internal/isAlive
    initialDelay: 10
  readiness:
    path: /okonomiportalen/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "0155880b-f708-4f61-ade8-00931fe41b89" # 0000-GA-SOKOS-CHAPPAI
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
  accessPolicy:
    outbound:
      rules:
        - application: sokos-mikrofrontend-api
        - application: sokos-postering-api
      external:
        - host: sokos-skattekort-person.dev-fss-pub.nais.io
  ingresses:
    - "https://okonomiportalen.intern.dev.nav.no"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  env:

  # Mikrofrontend-template
  - name: AD_GRUPPE_SOKOS_MF_MIKROFRONTEND_READ
    value: 1b717a23-d376-471c-9fc6-356299fadc2b
  # Backends
  - name: SOKOS_MIKROFRONTEND_API
    value: http://sokos-mikrofrontend-api
  - name: SOKOS_MIKROFRONTEND_API_SCOPE
    value: api://dev-gcp.okonomi.sokos-mikrofrontend-api/.default
  - name: SOKOS_MIKROFRONTEND_PROXY
    value: "/mikrofrontend-api"
  - name: SOKOS_POSTERING_API
    value: http://sokos-postering-api
  - name: SOKOS_POSTERING_API_SCOPE
    value: api://dev-gcp.okonomi.sokos-postering-api/.default
  - name: SOKOS_POSTERING_PROXY
    value: "/postering-api"

  # Utbetalinger
  - name: AD_GRUPPE_SOKOS_MF_UTBETALINGER_READ
    value: b01fb216-fcb3-4ede-b7da-71fffe859763

  # Skattekort
  - name: AD_GRUPPE_SOKOS_MF_SKATTEKORT_READ
    value: a13b4176-e328-4e1c-b181-ff676a7146b1
  - name: SOKOS_SKATTEKORT_PERSON_API
    value: https://sokos-skattekort-person.dev-fss-pub.nais.io
  - name: SOKOS_SKATTEKORT_PERSON_API_SCOPE
    value: api://dev-fss.okonomi.sokos-skattekort-person/.default
  - name: SOKOS_SKATTEKORT_PROXY
    value: "/skattekort-api"