apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-utbetalingsportalen
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  liveness:
    path: /utbetalingsportalen/internal/isAlive
    initialDelay: 10
  readiness:
    path: /utbetalingsportalen/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "1b717a23-d376-471c-9fc6-356299fadc2b" # 0000-GA-SOKOS-MF-Mikrofrontend-READ
          - id: "a13b4176-e328-4e1c-b181-ff676a7146b1" # 0000-GA-SOKOS-MF-Skattekort-READ
          - id: "b01fb216-fcb3-4ede-b7da-71fffe859763" # 0000-GA-SOKOS-MF-ORS-READ
          - id: "98146b9a-1891-44e3-9b61-92130c2fcd8b" # 0000-GA-SOKOS-MF-KRP-READ
          - id: "e0023d91-26bc-4d5d-95ba-3148b6123afc" # 0000-GA-SOKOS-MF-OppdragsInfo-READ
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
  accessPolicy:
    outbound:
      rules:
        - application: sokos-mikrofrontend-api
        - application: sokos-up-ors-api
        - application: sokos-nav-oppdrag-api
        - application: sokos-up-krp-api
      external:
        - host: sokos-skattekort-person.dev-fss-pub.nais.io
  ingresses:
    - "https://utbetalingsportalen.intern.dev.nav.no"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  env:

  # Mikrofrontend-template
  - name: SOKOS_MIKROFRONTEND_API
    value: http://sokos-mikrofrontend-api
  - name: SOKOS_MIKROFRONTEND_API_SCOPE
    value: api://dev-gcp.okonomi.sokos-mikrofrontend-api/.default
  - name: SOKOS_MIKROFRONTEND_PROXY
    value: "/mikrofrontend-api"

  # sokos-up-ors-api
  - name: SOKOS_UP_ORS_API
    value: http://sokos-up-ors-api
  - name: SOKOS_UP_ORS_API_SCOPE
    value: api://dev-gcp.okonomi.sokos-up-ors-api/.default
  - name: SOKOS_UP_ORS_API_PROXY
    value: "/up-ors-api"

  # Skattekort
  - name: SOKOS_SKATTEKORT_PERSON_API
    value: https://sokos-skattekort-person.dev-fss-pub.nais.io
  - name: SOKOS_SKATTEKORT_PERSON_API_SCOPE
    value: api://dev-fss.okonomi.sokos-skattekort-person/.default
  - name: SOKOS_SKATTEKORT_PROXY
    value: "/skattekort-api"

  # sokos-nav-oppdrag
  - name: SOKOS_NAV_OPPDRAG_API
    value: https://sokos-nav-oppdrag.dev-fss-pub.nais.io
  - name: SOKOS_NAV_OPPDRAG_API_SCOPE
    value: api://dev-fss.okonomi.sokos-nav-oppdrag/.default
  - name: SOKOS_NAV_OPPDRAG_PROXY
    value: "/nav-oppdrag-api"

  # sokos-up-krp-api
  - name: SOKOS_UP_KRP_API
    value: http://sokos-up-krp-api
  - name: SOKOS_UP_KRP_API_SCOPE
    value: api://dev-gcp.okonomi.sokos-up-krp-api/.default
  - name: SOKOS_UP_KRP_API_PROXY
    value: "/up-krp-api"